[package]
name = "BattleZipsV2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
halo2_gadgets = "0.2.0"
halo2_proofs = "0.2.0"
plotters = "0.3.3"
proptest = "1.0.0"
